export { default as htmlDeserializerOptions } from '@plugins/htmlDeserializerOptions';
export { default as defaultToolbar } from '@plugins/defaultToolbar';
export { default as pluginParagraph } from '@plugins/pluginParagraph';
export { default as pluginText } from '@plugins/pluginText';
export { default as pluginMarks } from '@plugins/pluginMarks';
export { default as pluginLists } from '@plugins/pluginLists';
export { default as pluginHeadings } from '@plugins/pluginHeadings';
export { default as googleDocs } from '@plugins/pluginGoogleDocs';
export { default as msOffice } from '@plugins/pluginMsOffice';
